### ISSUE TITLE
Bumping a modal trigger, even while scrolling, opens modal on mobile

### ISSUE THREAD

**Issue by galengidman** [cferdinandi/modals#58]
I'm experiencing this on my own implementation as well as on the demo. While swiping/scrolling on mobile, if you so much as bump a modal trigger, the modal opens. This makes scrolling past modals with a large target almost impossible.

I've experienced this on iOS and Android.

**Comment by cferdinandi** [comment]
Hey, sorry for the delay on this. Good catch. I'll try to figure out what's going on here, but for expectation setting purposes, I have a few other priorities right now so it might take me a while.

**Comment by cferdinandi** [comment]
This should be fixed with v10.1.2, via https://github.com/cferdinandi/modals/pull/62

**Comment by cferdinandi** [comment]
In case you're curious how this was addressed: when a touch event happens, we track when it starts and ends, and how far (if at all) the touch location changes. 

If it's more than ~7-10px, we consider it a scroll or swipe and ignore it. Otherwise, we fire our event. This also prevents duplicate touch and click events.

**Comment by galengidman** [comment]
Can't thank you enough, Chris. Awesome work as always.
